### ISSUE TITLE
eleventy 3 support

### ISSUE THREAD

**Issue by pcarrier** [saneef/eleventy-plugin-asciidoc#20]
eleventy 3 doesn't appear supported.

```
pcarrier@cat ~/s/blog> cupa package.json .eleventy.js
--- 8< --- 8< --- package.json --- 8< --- 8< ---
{
  "name": "blog",
  "private": true,
  "type": "module",
  "scripts": {
    "start": "eleventy --serve"
  },
  "devDependencies": {
    "@11ty/eleventy": "3.0.0-alpha.18",
    "eleventy-plugin-asciidoc": "^4.0.2"
  }
}
--- 8< --- 8< --- .eleventy.js --- 8< --- 8< ---
import asciidoc from "eleventy-plugin-asciidoc";

export function config(e) {
  e.addPlugin(asciidoc);
}
--- >8 --- >8 --- >8 --- >8 --- >8 ---
```

```
pcarrier@cat ~/s/blog> pnpm start

> blog@ start /Users/pcarrier/src/blog
> eleventy --serve

[11ty] Eleventy Error (CLI):
[11ty] Cannot read properties of undefined (reading 'templateFormats') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'templateFormats')
[11ty]     at TemplateConfig.mergeConfig (file:///Users/pcarrier/src/blog/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.18/node_modules/@11ty/eleventy/src/TemplateConfig.js:457:17)
[11ty]     at async TemplateConfig.init (file:///Users/pcarrier/src/blog/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.18/node_modules/@11ty/eleventy/src/TemplateConfig.js:210:17)
[11ty]     at async Eleventy.initializeConfig (file:///Users/pcarrier/src/blog/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.18/node_modules/@11ty/eleventy/src/Eleventy.js:246:3)
[11ty]     at async Eleventy.init (file:///Users/pcarrier/src/blog/node_modules/.pnpm/@11ty+eleventy@3.0.0-alpha.18/node_modules/@11ty/eleventy/src/Eleventy.js:476:4)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pcarrier** [comment]
My mistake

**Comment by saneef** [comment]
Glad to know it is working with Eleventy 3.0. I haven't tested the plugin with v3 yet.

I know, I should be doing it. Will try to find some time this weekend to test it.
